name: Deploy Website

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2

      - name: github pages
        uses: actions/configure-pages@v6.0.0

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v5.0.0
        with: 
          path: .

      - name: Deploy
        uses: actions/deploy-pages@v4
        
      

    
